//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: User.proto
namespace tutorial
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"User")]
  public partial class User : global::ProtoBuf.IExtensible
  {
    public User() {}
    
    private int _uid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"uid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int uid
    {
      get { return _uid; }
      set { _uid = value; }
    }
    private string _id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string id
    {
      get { return _id; }
      set { _id = value; }
    }
    private string _pw;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"pw", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string pw
    {
      get { return _pw; }
      set { _pw = value; }
    }
    private string _nick = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"nick", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string nick
    {
      get { return _nick; }
      set { _nick = value; }
    }
    private int _gameNum;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"gameNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int gameNum
    {
      get { return _gameNum; }
      set { _gameNum = value; }
    }
    private int _winNum;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"winNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int winNum
    {
      get { return _winNum; }
      set { _winNum = value; }
    }
    private readonly global::System.Collections.Generic.List<string> _replay = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(7, Name=@"replay", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> replay
    {
      get { return _replay; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}